module.exports = {
    api: require('./api'),
    execute: require('./execute'),
    executor: require('./executor'),
    eventListener: require('./eventListener'),
    onEvent: require('./onEvent'),
    onCommand: require('./onCommand'),
    onMessage: require('./onMessage'),
    onUse: require('./onUse'),
    onEdit: require('./onEdit'),
    onMention: require('./onMention'),
    onChat: require('./onChat'),
    onUser: require('./onUser'),
    obButton: require('./onButton'),
    uploadDocMessages: require('./upload/docsMessages'),
    uploadPhotoMessages: require('./upload/photoMessages'),
    uploadCover: require('./upload/cover'),
    getGroupId: require('./getGroupId'),
    getBuffer: require('../utils/getBuffer')
}